[[constraint]]
  name = "github.com/go-ble/ble"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "3.3.3"

[[constraint]]
  branch = "master"
  name = "github.com/fernet/fernet-go"
